"use client";
import {useId,useState} from 'react';
import {ArrowRight,ArrowUpRight,CalendarDays,CircleHelp,FileText,GitBranch,Orbit,ShieldCheck,Sparkles} from 'lucide-react';
import type {GraphNode,GraphEdge,Deal,TimelineEvent} from '@/lib/contracts';
import {adjacent,entityDescriptions,relationDescriptions,nodeEventIds,type GraphSelection} from '@/lib/universe';
import {display,dateDisplay} from '@/lib/display';
import EvidencePanel,{Sources} from './evidence';
type Props={selection:GraphSelection;nodes:GraphNode[];edges:GraphEdge[];events:TimelineEvent[];date:string;deal:Deal;onNavigate:(id:string)=>void;onSource:(id:string)=>void;onAsk:()=>void;evidenceId:string|null};
const verificationLabel=(status:string)=>status==='verified'?'Verified against a source':status==='inferred'?'Inferred':status==='ambiguous'?'Ambiguous · needs review':status+' · verification not established';
export default function ContextInspector({selection,nodes,edges,events,date,deal,onNavigate,onSource,onAsk,evidenceId}:Props){
 const [tab,setTab]=useState('relations'),id=useId();const node=selection.kind==='node'?nodes.find(n=>n.id===selection.id):null,edge=selection.kind==='edge'?edges.find(e=>e.id===selection.id):null;
 const links=node?adjacent(node.id,nodes,edges):[],source=node?.evidence_ids??edge?.evidence_ids??[],type=node?.type??'Relationship',title=display(node?.label??edge?.type.replaceAll('_',' ')??'Context unavailable');
 const refs=node?nodeEventIds(node):edge?.event_ids??[],linkedEvents=events.filter(e=>refs.includes(e.event_id));
  const eventDate=linkedEvents.length===1?linkedEvents[0].date:null;
 function openSource(sourceId:string){onSource(sourceId);setTab('evidence')}
 return <div className="context-inspector"><div className="inspector-heading"><div className={'inspector-orb planet-'+type.toLowerCase()}><Orbit size={22}/></div><span className="eyebrow">{type} · CONTEXT EXPLORER</span><h3>{title}</h3><code className="inspector-id">{node?.id??edge?.id??'ID unavailable'}</code><div className="inspector-date"><CalendarDays size={12}/>{eventDate?'Event · '+dateDisplay(eventDate)+' / ':''}As of {dateDisplay(date)}</div></div>
 <div className="inspector-ask"><div><Sparkles size={16}/><span>Make sense of this connection.</span></div><button className="button primary" onClick={onAsk}>Ask Copilot<ArrowUpRight size={15}/></button></div>
 <div className="inspector-tabs" role="tablist" aria-label="Entity details"><button role="tab" id={id+'-relations-tab'} aria-selected={tab==='relations'} aria-controls={id+'-relations'} className={tab==='relations'?'active':''} onClick={()=>setTab('relations')}><GitBranch size={14}/>Entity & connections</button><button role="tab" id={id+'-evidence-tab'} aria-selected={tab==='evidence'} aria-controls={id+'-evidence'} className={tab==='evidence'?'active':''} onClick={()=>setTab('evidence')}><FileText size={14}/>Source evidence</button></div>
 <div id={id+'-relations'} role="tabpanel" aria-labelledby={id+'-relations-tab'} hidden={tab!=='relations'} className="inspector-body"><span className={'badge '+((node?.verification??edge?.verification)==='verified'?'teal':'blue')}><ShieldCheck size={12}/>{verificationLabel(node?.verification??edge?.verification??'unknown')}</span>
 <p className="entity-explanation">{node?entityDescriptions[node.type]??'An entity present in this graph snapshot. Inspect its source to understand its meaning.':edge?relationDescriptions[edge.type]??'Relationship type supplied by the graph API. Inspect sources before drawing further conclusions.':'This entity is unavailable in the current scope.'}</p>
 {node?.subtitle&&<div className="inspector-fact"><span>Graph detail</span><strong>{display(node.subtitle)}</strong></div>}
  {node?.source&&<dl className="inspector-facts"><div><dt>Entity ID</dt><dd>{node.entity_id}</dd></div><div><dt>Label state</dt><dd>{node.source.label.state}</dd></div><div><dt>Label limitations</dt><dd>{node.source.label.limitations.join(' ')||'None supplied'}</dd></div><div><dt>Validity</dt><dd>{node.source.validity.valid_from??'Unknown start'} / {node.source.validity.valid_to??node.source.validity.open_end_reason??'Unknown end'} · {node.source.validity.temporal_basis}</dd></div></dl>}
  {refs.length>0&&<div className="inspector-fact"><span>Linked events · {refs.length}</span>{refs.map(ref=>{const event=events.find(e=>e.event_id===ref);return <p key={ref}><code>{ref}</code>{event&&<> · {dateDisplay(event.date)} · {event.source?.scope_kind??'Source context'}{event.source?.scope_kind==='account'&&' (not a direct deal claim)'}</>}</p>})}</div>}
  {edge?.provenance&&<p className="small muted">Match method: {edge.provenance.match_method} · Temporal basis: {edge.provenance.validity.temporal_basis}</p>}
 {node?.type==='Deal'&&(node.entity_id??node.id)===deal.deal_id&&<dl className="inspector-facts"><div><dt>Stage</dt><dd>{display(deal.stage??'Historical stage unknown')}</dd></div><div><dt>Owner</dt><dd>{display(deal.owner)}</dd></div><div><dt>Potential ACV</dt><dd>{deal.acv===null?'Unknown':'IDR '+deal.acv.toLocaleString('en-US')}</dd></div><div><dt>Fact scope</dt><dd>{deal.temporal_scope}</dd></div></dl>}
 <div className="inspector-section-title"><h4>{node?'Connected to':'Relationship endpoints'}</h4><span className="count-badge">{node?links.length:edge?2:0}</span></div>
 {node&&links.length===0&&<p className="muted small">No connections in the loaded subgraph. This does not establish that no other relationships exist.</p>}
 {links.map(({edge:relation,neighbor,direction})=><div className="connection-card" key={relation.id}><button className="connection-node" onClick={()=>onNavigate(neighbor.id)}><i className={'planet-swatch planet-'+neighbor.type.toLowerCase()}/><span><small>{neighbor.type}</small><strong>{display(neighbor.label)}</strong></span><ArrowUpRight size={15}/></button><div className="relation-direction"><ArrowRight size={12}/><span>{direction==='outgoing'?'Outgoing':'Incoming'} · {relation.type}</span></div><p>{relationDescriptions[relation.type]??'A connection matching the supplied relationship type.'}</p><span className={'relation-verification '+(relation.verification==='verified'?'':'muted')}>{verificationLabel(relation.verification)}</span><Sources ids={relation.evidence_ids} onOpen={openSource}/></div>)}
 {edge&&[edge.source,edge.target].map((nodeId,i)=>{const endpoint=nodes.find(n=>n.id===nodeId);return endpoint?<button className="connection-node endpoint-card" key={nodeId} onClick={()=>onNavigate(nodeId)}><i className={'planet-swatch planet-'+endpoint.type.toLowerCase()}/><span><small>{i===0?'From':'To'} · {endpoint.type}</small><strong>{display(endpoint.label)}</strong></span><ArrowUpRight size={15}/></button>:null})}
 <div className="inspector-section-title"><h4>Entity sources</h4><span className="count-badge">{source.length}</span></div>{source.length?<Sources ids={source} onOpen={openSource}/>:<p className="small muted">No direct source is available. Inspect connection evidence; do not assume this is a fully evidenced dated fact.</p>}
 <div className="callout neutral"><CircleHelp size={15}/><span>Planet color represents entity type. Size, distance, and glow are visual layout, not score, importance, or confidence.</span></div></div>
 <div id={id+'-evidence'} role="tabpanel" aria-labelledby={id+'-evidence-tab'} hidden={tab!=='evidence'}><EvidencePanel id={evidenceId??source[0]??null} date={date} expectedMeta={deal.meta}/></div></div>;
}
