"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, ArrowUpRight, BriefcaseBusiness, CalendarDays, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Database, FileText, GitCompareArrows, LayoutDashboard, MapPin, Network, RefreshCw, Search, Settings2, ShieldCheck, Sparkles, Target, TrendingUp, UserRound, X, AlertTriangle, Info, PanelLeftClose, Menu, Orbit } from "lucide-react";
import type { ContextBundle, DealsResponse, TimelineEvent } from "@/lib/contracts";
import { api } from "@/lib/client";
import { validDate } from "@/lib/domain";
import EvidencePanel, { Sources } from "./evidence";
import Dialog from "./dialog";
import CopilotDrawer from "./copilot-drawer";
import UniverseNavigator from "./universe-navigator";
import type { ChatEntity } from "./chat-context";
import { display } from "@/lib/display";
import Compare from "./comparison";
import ContextInspector from "./context-inspector";
import type { GraphSelection } from "@/lib/universe";
const Graph=dynamic(()=>import("./context-graph"),{ssr:false,loading:()=> <div className="graph-placeholder" role="status"><Network size={32}/><p>Preparing your universe…</p></div>});
const money=(n:number|null)=>n===null?"—":new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const dateLabel=(date:string)=>new Date(date+"T12:00:00").toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"});
const initials=(name:string)=>name.split(" ").slice(0,2).map(n=>n[0]).join("");
const score=(n:number|null)=>n===null?<span className="na">Unavailable</span>:<span className="table-score">{n}<small>/100</small></span>;
function Coverage({count}:{count:number}){return <span className="coverage"><span className="coverage-bars">{[0,1,2,3,4].map(i=><i key={i} className={i<count?"filled":""}/>)}</span><span>{count}/5</span></span>;}
function Loading(){return <div className="data-loading" role="status">{[1,2,3,4].map(n=><div key={n} className="skeleton block"/>)}<span className="sr-only">Loading context for the selected date</span></div>;}
export default function Workspace({dealId}:{dealId?:string}){
  const [date,setDate]=useState("2026-10-01"),[ready,setReady]=useState(false),[loadedSummary,setSummary]=useState<DealsResponse|null>(null),[loadedContext,setContext]=useState<ContextBundle|null>(null),[error,setError]=useState(""),[retry,setRetry]=useState(0);
  const [search,setSearch]=useState(""),[stage,setStage]=useState(""),[owner,setOwner]=useState(""),[coverageFilter,setCoverageFilter]=useState(""),[sort,setSort]=useState("urgency"),[eventType,setEventType]=useState(""),[actor,setActor]=useState(""),[eventStatus,setEventStatus]=useState("");
  const [eventId,setEventId]=useState<string|null>(null),[evidenceId,setEvidenceId]=useState<string|null>(null),[evidenceDate,setEvidenceDate]=useState(date),[sourceModal,setSourceModal]=useState(false),[assessment,setAssessment]=useState<string|null>(null),[copilotModal,setCopilotModal]=useState(false),[help,setHelp]=useState(false),[collapsed,setCollapsed]=useState(false);
  const [graphSelection,setGraphSelection]=useState<GraphSelection|null>(null);
  const [copilotScope,setCopilotScope]=useState<{entity:ChatEntity;date:string;dealId:string}|null>(null),[evidenceLibrary,setEvidenceLibrary]=useState(false),[profile,setProfile]=useState(false);
  const [pane,setPane]=useState("graph"),[tab,setTab]=useState("compare"),[filtersVisible,setFiltersVisible]=useState(false);
  useEffect(()=>{
    const query=new URLSearchParams(window.location.search),asOf=query.get("as_of");
    if(asOf&&validDate(asOf)&&asOf<="2026-10-01"&&asOf>="2024-01-01")setDate(asOf);
    setEventId(query.get("event"));if(query.get("tab")==="copilot")setCopilotModal(true);
    try{const saved=sessionStorage.getItem("relio-list-filters");if(saved){const f=JSON.parse(saved);setSearch(f.search??"");setStage(f.stage??"");setOwner(f.owner??"");setSort(f.sort??"urgency");setCoverageFilter(f.coverageFilter??"");}}catch{}
    setReady(true);
    function pop(){const q=new URLSearchParams(window.location.search);const d=q.get("as_of");if(d&&validDate(d))setDate(d);}
    window.addEventListener("popstate",pop);return ()=>window.removeEventListener("popstate",pop);
  },[]);
  useEffect(()=>{if(ready)sessionStorage.setItem("relio-list-filters",JSON.stringify({search,stage,owner,sort,coverageFilter}));},[search,stage,owner,sort,coverageFilter,ready]);
  useEffect(()=>{
    if(!ready)return;
    const controller=new AbortController();setError("");setSummary(null);setContext(null);setEvidenceId(null);setEventId(null);setGraphSelection(null);setSourceModal(false);setEventType("");setActor("");setEventStatus("");
    (dealId?api.context(dealId,date,controller.signal):api.deals(date,controller.signal)).then(data=>{
      if(controller.signal.aborted)return;
      if(dealId){const bundle=data as ContextBundle;setContext(bundle);const qId=new URLSearchParams(window.location.search).get("event");const selected=bundle.timeline.find(e=>e.event_id===qId)??bundle.timeline.at(-1);setEventId(selected?.event_id??null);setEvidenceId(selected?.evidence_ids[0]??null);setEvidenceDate(date);}
      else setSummary(data as DealsResponse);
    }).catch(e=>{if(!controller.signal.aborted)setError(e.message);});
    return ()=>controller.abort();
  },[date,dealId,retry,ready]);
  function changeDate(next:string){if(next===date||!validDate(next)||next>"2026-10-01"||next<"2024-01-01")return;setDate(next);const query=new URLSearchParams(window.location.search);query.set("as_of",next);query.delete("event");window.history.pushState(null,"","?"+query.toString());}
  function selectEvent(event:TimelineEvent){setGraphSelection(null);setEventId(event.event_id);setEvidenceId(event.evidence_ids[0]??null);setEvidenceDate(date);const q=new URLSearchParams(window.location.search);q.set("event",event.event_id);q.set("as_of",date);window.history.replaceState(null,"","?"+q.toString());}
  function source(id:string,sourceDate=date){setGraphSelection(null);setEvidenceId(id);setEvidenceDate(sourceDate);setSourceModal(true);}
  function openTab(next:string){if(next==="copilot"){askCopilot();return;}setTab(next);const q=new URLSearchParams(window.location.search);q.set("tab",next);window.history.replaceState(null,"","?"+q.toString());}
  const summary=loadedSummary?.scope.as_of===date?loadedSummary:null;
  const context=loadedContext?.scope.as_of===date?loadedContext:null;
  const deals=useMemo(()=>{
    const result=(summary?.deals??[]).filter(d=>(d.name+" "+d.account_id+" "+d.deal_id).toLowerCase().includes(search.toLowerCase())&&(!stage||d.stage===stage)&&(!owner||d.owner_id===owner)&&(!coverageFilter||(coverageFilter==="complete"?d.coverage===5:d.coverage<5)));
    const key=sort as "urgency"|"attractiveness"|"acv";
    return result.sort((a,b)=>{if(a[key]===null&&b[key]!==null)return 1;if(b[key]===null&&a[key]!==null)return -1;return (b[key]??0)-(a[key]??0)||(b.acv??0)-(a.acv??0)||a.deal_id.localeCompare(b.deal_id);});
  },[summary,search,stage,owner,coverageFilter,sort]);
  const events=(context?.timeline??[]).filter(e=>(!eventType||e.type===eventType)&&(!actor||e.actor===actor)&&(!eventStatus||e.status===eventStatus));
  const selected=context?.timeline.find(e=>e.event_id===eventId);
  const loading=!error&&(!ready||(!summary&&!context));
  const all=summary?.deals??[],knownAcv=all.filter(d=>d.acv!==null),totalAcv=knownAcv.reduce((sum,d)=>sum+(d.acv??0),0),currentDeal=context?.deal;
  function inspectNode(id:string){const node=context?.graph.nodes.find(n=>n.id===id);if(!node)return;const event=context?.timeline.find(e=>e.event_id===node.event_id);if(event)selectEvent(event);setGraphSelection({kind:"node",id});setEvidenceId(node.evidence_ids[0]??null);setEvidenceDate(date);setSourceModal(true);}
  function inspectorSource(id:string){setEvidenceId(id);setEvidenceDate(date);}
  function askCopilot(){const choice=graphSelection??(eventId?{kind:'node' as const,id:eventId}:null),node=choice?.kind==='node'?context?.graph.nodes.find(n=>n.id===choice.id):null,edge=choice?.kind==='edge'?context?.graph.edges.find(e=>e.id===choice.id):null;const entity=node?{id:node.id,type:node.type,label:display(node.label),evidenceIds:[...node.evidence_ids]}:edge?{id:edge.id,type:'Relationship',label:edge.type,evidenceIds:[...edge.evidence_ids]}:null;setCopilotScope(entity&&dealId?{entity,date,dealId}:null);setSourceModal(false);setCopilotModal(true);}
  useEffect(()=>{if(context&&window.location.hash==='#approaches')requestAnimationFrame(()=>document.getElementById('approaches')?.scrollIntoView({block:'start'}));},[context]);
  const explorerDeal=dealId??all.find(d=>d.deal_id==='DL-004')?.deal_id??all[0]?.deal_id??'DL-004';
  const libraryIds=[...new Set(context?context.timeline.flatMap(e=>e.evidence_ids).concat(date==='2026-10-01'?['EVC-'+context.deal.deal_id]:[]):all.flatMap(d=>d.blocker_evidence_ids.concat(date==='2026-10-01'?['EVC-'+d.deal_id]:[])))];
  const inspector=context&&graphSelection?<ContextInspector key={graphSelection.kind+"-"+graphSelection.id} selection={graphSelection} nodes={context.graph.nodes} edges={context.graph.edges} events={context.timeline} date={date} onAsk={askCopilot} deal={context.deal} onNavigate={inspectNode} onSource={inspectorSource} evidenceId={evidenceId}/>:null;
  return <div className={"app-shell "+(collapsed?"nav-collapsed":"")+(copilotModal?" copilot-open":"")}>
    <a href="#main-content" className="skip-link">Skip to content</a>
    <aside className="sidebar"><Link className="brand" href={"/deals?as_of="+date} aria-label="Relio dashboard"><picture><source media="(max-width:1100px)" srcSet="/brand/relio-mark-reverse.svg"/><img src={"/brand/"+(collapsed?"relio-mark-reverse.svg":"relio-horizontal-reverse.svg")} alt="relio" width={collapsed?36:168} height={44}/></picture></Link>
      <div className="brand-universe-note"><Sparkles size={12}/>Your deal universe.</div><div className="sidebar-workspace"><div className="workspace-avatar"><BriefcaseBusiness size={17}/></div><div><strong>KasirNusa</strong><span>Sales workspace</span></div><ChevronDown size={14}/></div>
      <span className="nav-label">WORKSPACE</span><nav aria-label="Main navigation"><Link aria-label="Dashboard" className={'nav-item '+(!dealId?'active':'')} href={'/deals?as_of='+date}><LayoutDashboard size={19}/><span>Dashboard</span></Link><Link aria-label="Deal Universe" className={'nav-item '+(dealId?'active':'')} href={'/deals/'+explorerDeal+'?as_of='+date}><Orbit size={19}/><span>Deal Universe</span></Link><button aria-label="Copilot" className={'nav-item '+(copilotModal?'active':'')} onClick={askCopilot}><Sparkles size={19}/><span>Copilot</span><span className="ai-chip">AI</span></button><span className="nav-label nav-section">RESEARCH</span><button aria-label="Evidence library" className="nav-item" onClick={()=>setEvidenceLibrary(true)}><ShieldCheck size={19}/><span>Evidence</span></button><Link aria-label="Approaches" className="nav-item" href={'/deals/'+explorerDeal+'?as_of='+date+'#approaches'}><GitCompareArrows size={19}/><span>Approaches</span></Link></nav>
      <div className="nav-bottom"><div className="sidebar-note"><span className="status-dot"/><strong>Source-backed workspace</strong><p>KasirNusa · 1 Oct 2026 snapshot</p></div><button aria-label="Workspace guide" className="nav-item" onClick={()=>setHelp(true)}><CircleHelp size={18}/><span>Workspace guide</span></button><button className="nav-item collapse-control" onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?'Expand navigation':'Collapse navigation'}>{collapsed?<Menu size={18}/>:<PanelLeftClose size={18}/>}<span>Collapse navigation</span></button><button className="profile" aria-label="Andi Wiratama profile" onClick={()=>setProfile(true)}><div className="avatar">AW</div><div><strong>Andi Wiratama</strong><span>VP Sales</span></div><ChevronDown size={14}/></button></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb"><span>Workspace</span><ChevronRight size={13}/><Link href={"/deals?as_of="+date}>Dashboard</Link>{dealId&&<><ChevronRight size={13}/><strong>{currentDeal?.account_id??dealId}</strong></>}</div><div className="topbar-actions"><span className="topbar-status"><span className="status-dot"/>Read-only</span><button className="icon-button" aria-label="Open workspace guide" onClick={()=>setHelp(true)}><CircleHelp size={19}/></button><button className="avatar small-avatar" aria-label="Open VP Sales profile" onClick={()=>setProfile(true)}>AW</button></div></header>
      <main id="main-content" className="main-content"><div className="page-heading"><div>{dealId?<><Link className="back-link" href={"/deals?as_of="+date}><ArrowLeft size={14}/>Deal overview</Link><div className="detail-title"><h1>{currentDeal?.name??"Deal context"}</h1>{currentDeal?.stage&&<span className="badge blue">{display(currentDeal.stage)}</span>}</div><p className="detail-subtitle"><span className="mono">{dealId}{currentDeal?" · "+currentDeal.account_id:""}</span>{currentDeal&&<><span>·</span><MapPin size={13}/>{currentDeal.city}<span>·</span><UserRound size={13}/>{display(currentDeal.owner)}</>}</p></>:<><span className="eyebrow">SALES CONTEXT WORKSPACE</span><h1>See the universe behind every deal.</h1><p>Explore connections. Trace the evidence. Find a clearer next move.</p></>}</div><div className="heading-actions"><button className="button secondary" aria-label="Ask Copilot" data-copilot-trigger onClick={askCopilot}><Sparkles size={17}/>Ask Copilot</button><button className="icon-button refresh" aria-label="Refresh data" onClick={()=>setRetry(n=>n+1)}><RefreshCw size={17}/></button></div></div>
      <div className="snapshot-bar"><div className="snapshot-label"><Database size={16}/><strong>Context through time</strong><span className="snapshot-muted">Dataset snapshot · 1 Oct 2026</span></div><div className="date-controls"><label htmlFor="as-of"><CalendarDays size={15}/><span>As of</span></label><input id="as-of" aria-label="Context date" type="date" min="2024-01-01" max="2026-10-01" value={date} onChange={e=>changeDate(e.target.value)}/>{dealId&&context&&<div className="time-step"><button className="icon-button" aria-label="Previous event" disabled={!context.navigation?.previous} onClick={()=>context.navigation?.previous&&changeDate(context.navigation.previous)}><ChevronLeft size={17}/></button><button className="icon-button" aria-label="Next event" disabled={!context.navigation?.next} onClick={()=>context.navigation?.next&&changeDate(context.navigation.next)}><ChevronRight size={17}/></button></div>}</div></div>
      {dealId&&<UniverseNavigator dealId={dealId} date={date} onChange={changeDate}/>}
      {date!=="2026-10-01"&&<div className="callout amber temporal-notice" role="status"><Info size={17}/><span>Historical context on {dateLabel(date)}. Snapshot stage, ACV, and outlet figures are unavailable at this historical date.</span><button className="text-button" onClick={()=>changeDate("2026-10-01")}>Latest snapshot</button></div>}
      {error?<div className="empty error-state" role="alert"><AlertTriangle size={30}/><h2>Context could not be loaded</h2><p>{error}</p><div className="button-row"><button className="button primary" onClick={()=>setRetry(n=>n+1)}><RefreshCw size={15}/>Try again</button>{dealId&&<Link className="button secondary" href={"/deals?as_of="+date}>Back to dashboard</Link>}</div></div>:loading?<Loading/>:!dealId&&summary?<>
        <div className="overview-metrics"><article className="overview-card"><div className="metric-top"><span>Active deals</span><BriefcaseBusiness size={18}/></div><div className="metric-value">{all.length}<small>prospects</small></div><p>Priority KasirNusa prospects</p></article><article className="overview-card"><div className="metric-top"><span>Potential annual contract value</span><TrendingUp size={18}/></div><div className="metric-value money">{knownAcv.length?money(totalAcv):"—"}</div><p>{knownAcv.length?"Potential ACV · not realized revenue":"Snapshot facts unavailable"}</p></article><article className="overview-card"><div className="metric-top"><span>Strategic footprint</span><Target size={18}/></div><div className="metric-value">{date==="2026-10-01"?all.filter(d=>(d.outlets??0)>30).length:"—"}<small>deal</small></div><p>More than 30 planned outlets</p></article><article className="overview-card"><div className="metric-top"><span>Assessment status</span><ShieldCheck size={18}/></div><div className="metric-value status-value">{all.some(d=>d.readiness!==null)?all.filter(d=>d.readiness!==null).length+" deals assessed":"Awaiting JEV"}</div><p>{all.some(d=>d.readiness!==null)?"Readiness follows the JEV rubric":"Urgency and readiness are not assessed"}</p></article></div>
        <section id="deal-list" className="panel deal-panel"><div className="panel-heading"><div><h2>Deal overview <span className="count-badge">{all.length}</span></h2><p>The context you need before the next move.</p></div><span className="badge neutral"><Database size={12}/>{summary.scope.mode==="local"?"Source-backed local view":"Backend connected"}</span></div>
        <div className="list-toolbar"><div className="search-field"><Search size={17}/><input aria-label="Search deals" placeholder="Search company name or deal ID…" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch("")}><X size={14}/></button>}</div><div className="list-controls"><button className={"button secondary "+(filtersVisible?"selected":"")} aria-expanded={filtersVisible} onClick={()=>setFiltersVisible(v=>!v)}><Settings2 size={16}/>Filter{(stage||owner||coverageFilter)&&<i className="filter-dot"/>}</button><label className="sort-control"><span>Sort by:</span><select aria-label="Sort deals" value={sort} onChange={e=>setSort(e.target.value)}><option value="urgency">Urgency</option><option value="attractiveness">Attractiveness</option><option value="acv">Highest ACV</option></select></label></div></div>
        {filtersVisible&&<div className="filter-row"><label>Stage<select value={stage} onChange={e=>setStage(e.target.value)}><option value="">All stages</option>{[...new Set(all.flatMap(d=>d.stage?[d.stage]:[]))].map(v=><option key={v} value={v}>{display(v)}</option>)}</select></label><label>Sales<select value={owner} onChange={e=>setOwner(e.target.value)}><option value="">All sales owners</option>{[...new Set(all.map(d=>d.owner_id))].map(id=><option value={id} key={id}>{all.find(d=>d.owner_id===id)?.owner}</option>)}</select></label><label>Evidence coverage<select value={coverageFilter} onChange={e=>setCoverageFilter(e.target.value)}><option value="">Any coverage</option><option value="complete">5/5 dimensions</option><option value="partial">Incomplete</option></select></label><button className="text-button" onClick={()=>{setStage("");setOwner("");setCoverageFilter("");setSearch("");}}>Reset filters</button></div>}
        {deals.length===0?<div className="empty"><Search size={26}/><h3>No matching deals</h3><p>Try a different search or filter.</p><button className="button secondary" onClick={()=>{setSearch("");setStage("");setOwner("");setCoverageFilter("");}}>Reset filters</button></div>:<>
        {sort==="urgency"&&deals.every(d=>d.urgency===null)&&<div className="insufficient-banner"><Info size={14}/>Urgency is unavailable. Deals are temporarily ordered by known ACV, not urgency.</div>}
        <div className="table-wrap"><table className="deal-table"><thead><tr><th>COMPANY / DEAL</th><th>STAGE & OWNER</th><th>POTENTIAL ACV</th><th>ATTRACTIVENESS</th><th>URGENCY</th><th>READINESS</th><th>EVIDENCE</th><th aria-label="Open context"/></tr></thead><tbody>{deals.map(d=><tr key={d.deal_id}><td><Link className="company-link" href={"/deals/"+d.deal_id+"?as_of="+date}><span className={"company-icon company-"+d.account_id}>{initials(d.name)}</span><span><strong>{d.name}</strong><span className="company-meta mono">{d.account_id} / {d.deal_id}</span></span></Link>{d.blocker&&<p className="row-blocker" title={d.blocker}><AlertTriangle size={10}/>{d.blocker}</p>}</td><td><span className={"badge "+(d.stage?"blue":"neutral")}>{d.stage?display(d.stage):"Stage unknown"}</span><span className="cell-subtitle">{display(d.owner)}</span><span className="small muted">{d.stage_since?Math.floor((Date.parse(date)-Date.parse(d.stage_since))/86400000)+" days in stage":"Stage history unavailable"}</span></td><td><strong className="acv">{money(d.acv)}</strong><span className="cell-subtitle">{d.outlets===null?"Outlet count unknown":d.outlets+" planned outlets"}</span></td><td><button className="score-button" onClick={()=>{setAssessment("Attractiveness");setEvidenceId("EVC-"+d.deal_id);setEvidenceDate(date);}} aria-label={"Explain attractiveness for "+d.name}>{score(d.attractiveness)}</button></td><td>{score(d.urgency)}</td><td>{d.readiness_label??<span className="na">Not assessed</span>}</td><td><Coverage count={d.coverage}/><span className="cell-subtitle">{d.action_count} historical options</span></td><td><Link className="icon-button table-open" href={"/deals/"+d.deal_id+"?as_of="+date} aria-label={"View context for "+d.name}><ArrowUpRight size={19}/></Link></td></tr>)}</tbody></table></div>
        <div className="mobile-deals">{deals.map(d=><article className="mobile-deal" key={d.deal_id}><Link href={"/deals/"+d.deal_id+"?as_of="+date}><span className="company-icon">{initials(d.name)}</span><div><strong>{d.name}</strong><span className="company-meta">{d.account_id} · {d.stage?display(d.stage):"Historical stage unknown"}</span></div><ArrowUpRight size={18}/></Link><dl><div><dt>Sales</dt><dd>{display(d.owner)}</dd></div><div><dt>Potential ACV</dt><dd>{money(d.acv)}</dd></div><div><dt>Planned outlets</dt><dd>{d.outlets??"Unknown"}</dd></div><div><dt>Attractiveness</dt><dd>{d.attractiveness===null?"Unavailable":d.attractiveness+"/100"}</dd></div><div><dt>Urgency / readiness</dt><dd>{d.urgency??"Not assessed"} / {d.readiness_label??"Not assessed"}</dd></div><div><dt>Time in stage</dt><dd>{d.stage_since?Math.floor((Date.parse(date)-Date.parse(d.stage_since))/86400000)+" days":"Unknown"}</dd></div><div><dt>Evidence / historical options</dt><dd>{d.coverage}/5 · {d.action_count} options</dd></div><div><dt>Blocker</dt><dd>{d.blocker??"Unknown"}</dd></div></dl></article>)}</div>
        </>}
        <div className="table-footer"><span>Showing {deals.length} of {all.length} deal</span><span><ShieldCheck size={13}/>Scores are not closing probabilities</span></div></section>
        <div className="overview-bottom"><section className="start-card"><div className="start-icon"><Network size={26}/></div><div><span className="eyebrow">START EXPLORING</span><h3>The decision lives in the details.</h3><p>See who requested what, when, and from which source.</p></div><Link className="button primary" href={"/deals/DL-004?as_of="+date}>Explore P04<ArrowRight size={16}/></Link></section><section className="data-note"><Database size={20}/><div><h3>Transparent from the source</h3><p>Records → context → evidence. Unknowns stay visible.</p><button className="text-button" onClick={()=>setHelp(true)}>About data & assessments<ArrowUpRight size={13}/></button></div></section></div>
      </>:context&&currentDeal?<>
        <div className="deal-facts"><span><strong>{money(currentDeal.acv)}</strong><small>potential ACV / year</small></span><span><strong>{currentDeal.outlets??"—"}</strong><small>planned outlets</small></span><span className="snapshot-fact"><Database size={14}/>CRM facts · snapshot only</span></div>
        <div className="assessment-grid">{[{title:"Attractiveness",value:currentDeal.attractiveness,icon:Target,description:"Contract value & footprint",kind:"Derived"},{title:"Urgency",value:currentDeal.urgency,icon:CalendarDays,description:"Purchase gate, deadline, follow-up",kind:currentDeal.urgency===null?"Not assessed":"Derived"},{title:"Readiness",value:currentDeal.readiness,icon:TrendingUp,description:currentDeal.readiness_label??"Five readiness levels · awaiting JEV",kind:currentDeal.readiness===null?"Not assessed":"JEV assessment"},{title:"Evidence coverage",value:null,icon:ShieldCheck,description:"Coverage across five information dimensions",kind:"Derived"}].map(item=><button className="assessment-card" key={item.title} onClick={()=>setAssessment(item.title)}><div className="metric-top"><span>{item.title}</span><item.icon size={18}/></div><div className="assessment-value">{item.title==="Evidence coverage"?<>{currentDeal.coverage}<small>/5</small></>:<>{item.value??"—"}{item.value!==null&&<small>/100</small>}</>}</div><p>{item.description}</p><div className="assessment-footer"><span className={"badge "+(item.value===null&&item.title!=="Evidence coverage"?"neutral":"blue")}>{item.kind}</span><span>Why this score?<ArrowUpRight size={12}/></span></div></button>)}</div>
        {currentDeal.blocker&&<div className="blocker-bar"><span className="blocker-icon"><AlertTriangle size={18}/></span><div><strong>Reported purchase gate</strong><p>{currentDeal.blocker}</p></div><Sources ids={currentDeal.blocker_evidence_ids} onOpen={source}/></div>}
        <div className="investigation-header"><div><h2>Explore the context</h2><span>Choose an event. Follow connections. Inspect sources.</span></div><span className="badge teal"><ShieldCheck size={12}/>Source-backed</span></div>
        <div className="context-tabs" role="tablist" aria-label="Investigation panels">{["timeline","graph","evidence"].map((p,i)=><button role="tab" aria-selected={pane===p} aria-controls={"pane-"+p} key={p} onClick={()=>setPane(p)} className={pane===p?"active":""}>{[<CalendarDays size={16} key="t"/>,<Network size={16} key="g"/>,<FileText size={16} key="e"/>][i]}{["Timeline","Graph","Evidence"][i]}</button>)}</div>
        <div className="investigation"><section id="pane-timeline" className={"panel timeline-panel "+(pane==="timeline"?"mobile-active":"")}><div className="compact-panel-heading"><h3><CalendarDays size={16}/>Timeline</h3><span className="count-badge">{context.timeline.length}</span></div><div className="timeline-filters"><label className="sr-only" htmlFor="event-type">Event type</label><select id="event-type" aria-label="Event type" value={eventType} onChange={e=>setEventType(e.target.value)}><option value="">All types</option>{[...new Set(context.timeline.map(e=>e.type))].map(v=><option key={v} value={v}>{display(v)}</option>)}</select><details><summary><Settings2 size={13}/>Actor & status</summary><label>Actor<select value={actor} onChange={e=>setActor(e.target.value)}><option value="">All actors</option>{[...new Set(context.timeline.map(e=>e.actor))].map(v=><option key={v} value={v}>{display(v)}</option>)}</select></label><label>Status<select value={eventStatus} onChange={e=>setEventStatus(e.target.value)}><option value="">All statuses</option>{[...new Set(context.timeline.map(e=>e.status))].map(v=><option key={v} value={v}>{display(v)}</option>)}</select></label></details></div>
        <div className="timeline-list">{events.length===0?<div className="empty"><p>No events match this filter or date.</p><button className="text-button" onClick={()=>{setEventType("");setActor("");setEventStatus("");}}>Reset filters</button></div>:events.map(event=><button key={event.event_id} className={"timeline-event "+(eventId===event.event_id?"selected":"")} onClick={()=>selectEvent(event)} aria-pressed={eventId===event.event_id}><span className="timeline-dot"><FileText size={13}/></span><time>{dateLabel(event.date)}</time><strong>{display(event.title)}</strong><p>{event.excerpt}</p><span className="event-actor"><UserRound size={11}/>{event.actor}</span><span className="event-bottom"><span className="event-type">{event.type.replaceAll("_"," ")}</span><span className="mono">{event.interaction_id}</span></span></button>)}</div><div className="timeline-footer">As-of {dateLabel(date)} · future events excluded</div></section>
        <section id="pane-graph" className={"panel graph-panel "+(pane==="graph"?"mobile-active":"")}><div className="compact-panel-heading"><h3><Sparkles size={17}/>Deal Universe</h3><span className="small muted">Select a planet to explore</span></div><Graph key={date+"-"+dealId} nodes={context.graph.nodes} edges={context.graph.edges} selectedEvent={eventId} selection={graphSelection} asOf={date} events={context.timeline} onAsk={askCopilot} onInspect={selection=>{setGraphSelection(selection);if(selection)setSourceModal(true);}} onSelect={(ids,event)=>{if(event){const selected=context.timeline.find(e=>e.event_id===event);if(selected)selectEvent(selected);}setEvidenceId(ids[0]??null);setEvidenceDate(date);}}/><div className="graph-footnote"><Info size={12}/>{context.graph.truncated?"Subgraph limited to the four latest events. ":""}Events connect to this deal through the source account.</div></section>
        <section id="pane-evidence" className={"panel evidence-panel "+(pane==="evidence"?"mobile-active":"")}><div className="compact-panel-heading"><h3><FileText size={16}/>{"Source evidence"}</h3>{evidenceId&&!graphSelection&&<span className="badge teal small-badge">Original source</span>}</div>{<EvidencePanel id={evidenceId} date={evidenceDate}/>}</section></div>
        <div className="selected-event-mobile"><FileText size={15}/><span>{selected?.title?display(selected.title):"No event selected"}</span>{evidenceId&&<button className="text-button" onClick={()=>setSourceModal(true)}>Open evidence<ArrowUpRight size={13}/></button>}</div>
        <section id="approaches" className="bottom-workspace panel"><Compare candidates={context.candidates} dealId={dealId!} date={date} version={context.scope.evidence_version+'|'+(context.catalogue_version??'unversioned')} onSource={id=>{source(id);setSourceModal(true);}}/></section>
      </>:null}
      <footer className="workspace-footer"><span>Your deal universe. A clearer mind.</span><span>Relio MVP · PRD v1.0 · GSM v3</span></footer>
      </main>
    </div>
    {sourceModal&&<Dialog title={graphSelection?"Context Explorer":evidenceDate!==date?"Evidence · scope "+evidenceDate:"Source evidence"} onClose={()=>setSourceModal(false)}>{inspector??<EvidencePanel id={evidenceId} date={evidenceDate}/>}</Dialog>}
    {assessment&&<Dialog title={"Why this score? · "+assessment} onClose={()=>setAssessment(null)}><div className="assessment-explanation"><span className="badge blue">{assessment==="Attractiveness"||assessment==="Evidence coverage"?"Derived from sources":"JEV assessment unavailable"}</span><h3>{assessment}</h3>
      {assessment==="Attractiveness"?<><p>Attractiveness combines potential ACV and strategic footprint at the snapshot date.</p><div className="formula mono">50% × relative ACV + 50% × strategic footprint</div><ul><li>Relative ACV = deal ACV ÷ maximum active prospect ACV × 100.</li><li>Strategic footprint = 100 for &gt;30 outlets; 0 for ≤30 known outlets.</li><li>Unknown values remain null. Snapshot facts are not backdated.</li></ul><Sources ids={date==="2026-10-01"?(currentDeal?["EVC-"+currentDeal.deal_id]:evidenceId?[evidenceId]:[]):[]} onOpen={id=>{source(id);setSourceModal(true);}}/><p className="small muted">rule-attractiveness-v1.0 · ordinal assessment, not win probability.</p></>:
      assessment==="Evidence coverage"?<><p>Number of evidenced dimensions out of five. This is not model confidence.</p><div className="coverage-dimensions">{currentDeal?.coverage_dimensions.map(d=><div key={d.key}><div><strong>{d.label} · {d.present?"Available":"Insufficient"}</strong><Sources ids={d.evidence_ids.slice(0,2)} onOpen={id=>{source(id);setSourceModal(true);}}/></div></div>)}</div><p className="small muted">coverage-v1.0 · local projection requires backend quality review.</p></>:
      assessment==="Readiness"?<><p>Readiness uses JEV Score on a five-level rubric:</p><ol start={0}><li>No evidence of intent</li><li>Early interest</li><li>Active evaluation</li><li>Commercial discussion</li><li>Explicit commitment / final gate</li></ol><div className="formula mono">readiness /100 = round(25 × JEV Score)</div><p>Ordinal labels follow the backend mapping. Local mode has no JEV invocation, so the result remains unavailable.</p></>:
      <><p>Urgency uses known factors: purchase gate 55%, deadline 25%, outstanding follow-up 20%.</p><p>Stage age is context, not an automatic urgency score. Approaching deadlines use the seven-day PRD threshold.</p><div className="callout amber"><Info size={16}/>Backend assessment and JEV are unavailable. Unknown values are not replaced with zero.</div></>}
      {context&&<details className="assessment-server"><summary>Assessment metadata & limitations</summary><p>Rubric: {context.assessment.rubric_version} · Status: {context.assessment.status}</p><p>{context.assessment.explanation}</p><ul>{context.assessment.unknowns.map(unknown=><li key={unknown}>{unknown}</li>)}</ul></details>}
      <p className="callout neutral"><Info size={16}/>Scores are rubric assessments, not Closed Won probabilities, realized revenue, or causal uplift.</p></div></Dialog>}
    {copilotModal&&<CopilotDrawer date={date} dealId={dealId??null} localMode={(context?.scope??summary?.scope)?.mode==='local'} entity={copilotScope?.date===date&&copilotScope.dealId===dealId?copilotScope.entity:null} onClose={()=>setCopilotModal(false)} onSource={(id,sourceDate)=>{source(id,sourceDate);setSourceModal(true);}}/>}
    {evidenceLibrary&&<Dialog title="Evidence library" onClose={()=>setEvidenceLibrary(false)}><div className="help-content"><p>Original records in your current workspace scope · {dateLabel(date)}.</p>{libraryIds.length?<Sources ids={libraryIds} onOpen={id=>{setEvidenceLibrary(false);source(id);}}/>:<p>No sources available at this date.</p>}<p className="small muted">Select a citation to inspect its source. Approval remains case-specific.</p></div></Dialog>}
    {profile&&<Dialog title="VP Sales workspace" onClose={()=>setProfile(false)}><div className="profile-card"><div className="avatar">AW</div><h3>Andi Wiratama</h3><span className="badge blue">VP Sales</span><p>KasirNusa · andi@kasirnusa.id</p><code>E01</code><p className="muted small">Demo persona from the employee dataset. Read-only workspace.</p></div></Dialog>}
    {help&&<Dialog title="About this workspace" onClose={()=>setHelp(false)}><div className="help-content"><img src="/brand/relio-horizontal-primary.svg" alt="relio" width={164} height={48}/><h3>Your deal universe. A clearer mind.</h3><p>Relio connects sales context with evidence you can inspect.</p><ol><li>Open a deal from the dashboard.</li><li>Choose a date and event in the timeline.</li><li>Explore planets and their connections.</li><li>Inspect the original source before drawing conclusions.</li><li>Select 2–4 historical approaches and compare them when JEV is connected.</li></ol><div className="callout neutral"><Database size={17}/><span>Synthetic KasirNusa data. Local mode reads the original workspace CSV/JSONL records.</span></div><p>JEV and Copilot are not connected in local mode. A precedent does not establish relevance, approval, execution, or consent for this deal.</p><p className="small muted">PRD Final MVP v1.0 · GSM v3 identity.</p></div></Dialog>}
  </div>;
}
