import { test, expect } from "@playwright/test";
const zoom=async(page:any)=>page.locator('.react-flow__viewport').evaluate((el:HTMLElement)=>new DOMMatrix(getComputedStyle(el).transform).a);
test('planet focus zoom, actual adjacency, source and neighbor navigation',async({page,request})=>{
  await page.goto('/deals/DL-004');await expect(page.locator('.react-flow__node')).toHaveCount(6);
  const response=await request.get('/api/deals/DL-004/graph?as_of=2026-10-01');const body=await response.json();
  await expect(page.locator('.solar-system[data-system-date="2026-09-22"]')).toContainText('22 Sept 2026');
  await expect(page.locator('.shared-system')).toContainText('As of 1 Oct 2026');
  await page.getByRole('button',{name:'All context',exact:true}).click();
  await expect(page.locator('.react-flow__node')).toHaveCount(body.nodes.length);
  await expect(page.locator('.dated-system')).toHaveCount(3);
  await expect(page.locator('.dated-system .solar-system-heading strong').first()).toHaveCSS('font-size','44px');
  await expect.poll(async()=>page.locator('.solar-system').last().evaluate(el=>el.getBoundingClientRect().bottom<document.querySelector('.universe-legend')!.getBoundingClientRect().top)).toBe(true);
  await page.locator('.graph-panel').screenshot({path:'../docs/frontend/qa/relio-solar-systems-1440.png'});
  const event=body.nodes.find((n:any)=>n.id==='EV-I0335');
  const neighbors=body.edges.filter((e:any)=>e.source===event.id||e.target===event.id);
  await expect.poll(()=>zoom(page)).toBeLessThan(.9);const before=await zoom(page);const planet=page.locator('.react-flow__node').filter({hasText:'Procurement update'});
  await expect(planet.locator('.planet-orb')).toHaveCSS('border-radius','50%');await planet.click();
  await expect(page.locator('.graph-container')).toHaveAttribute('data-selected-planet',event.id);
  await expect(page.locator('.context-inspector .connection-card')).toHaveCount(neighbors.length);
  await expect(page.locator('.inspector-id')).toHaveText(event.id);
  await expect.poll(()=>zoom(page)).toBeGreaterThan(before+.1);
  await page.keyboard.press('Escape');await page.locator('.graph-panel').screenshot({path:'../docs/frontend/qa/relio-universe-focus-1440.png'});await planet.click();
  await page.getByRole('dialog').screenshot({path:'../docs/frontend/qa/relio-universe-inspector-1440.png'});
  await page.getByRole('tab',{name:'Source evidence',exact:true}).click();await expect(page.getByRole('dialog').locator('.evidence-content blockquote')).toContainText('Kami tunda dulu');
  await page.getByRole('tab',{name:'Entity & connections',exact:true}).click();await page.locator('.connection-node').filter({hasText:'I0335'}).click();
  await expect(page.locator('.inspector-heading .eyebrow')).toContainText('Interaction');
  await page.keyboard.press('Escape');await page.getByLabel('Context date').fill('2026-09-21');await expect(page.locator('.timeline-event')).toHaveCount(2);
  await expect(page.locator('.context-inspector')).toHaveCount(0);await expect(page.locator('.graph-container')).toHaveAttribute('data-selected-planet','');
  await expect(page.locator('.graph-container')).not.toContainText('I0335');
});
test('keyboard planet, edge explanation and reduced motion without graph refetch',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/deals/DL-004');await expect(page.locator('.react-flow__node')).toHaveCount(6);
  const planet=page.locator('.react-flow__node').filter({hasText:'Procurement update'});await planet.focus();await page.keyboard.press('Enter');
  await expect(page.locator('.context-inspector')).toContainText('Connected to');await expect(page.locator('.graph-container')).toHaveAttribute('data-motion','reduced');
  let graphFetches=0;page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/deals/DL-004'))graphFetches++});
  await page.keyboard.press('Escape');await page.getByRole('button',{name:'All context',exact:true}).click();
  const edge=page.locator('.react-flow__edge').first();await edge.focus();await page.keyboard.press('Enter');
  await expect(page.locator('.context-inspector')).toContainText('Relationship endpoints');await expect(page.locator('.endpoint-card')).toHaveCount(2);
  expect(graphFetches).toBe(0);await expect(page.locator('.universe-stars')).toHaveCSS('animation-name','none');
});
test('mobile planet opens Context Explorer with source and restores focus',async({page})=>{
  await page.setViewportSize({width:375,height:950});await page.goto('/deals/DL-004');await page.getByRole('tab',{name:'Graph',exact:true}).click();
  await expect(page.locator('.react-flow__node')).toHaveCount(6);const planet=page.locator('.react-flow__node').filter({hasText:'Procurement update'});await planet.focus();await planet.click();
  const dialog=page.getByRole('dialog');await expect(dialog).toBeVisible();await expect(dialog).toContainText('Context Explorer');
  await expect(dialog.locator('.connection-card')).toHaveCount(2);await dialog.getByRole('tab',{name:'Source evidence',exact:true}).click();
  await expect(dialog.locator('blockquote')).toContainText('Kami tunda dulu');
  await dialog.screenshot({path:'../docs/frontend/qa/relio-universe-inspector-375.png'});await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();await expect(planet).toBeFocused();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);
});
